//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfInfoSecurity.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Juries()
        {
            this.Activities = new HashSet<Activities>();
            this.Activities1 = new HashSet<Activities>();
            this.Activities2 = new HashSet<Activities>();
            this.Activities3 = new HashSet<Activities>();
            this.Activities4 = new HashSet<Activities>();
        }
    
        public int Id { get; set; }
        public string Fio { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Phone { get; set; }
        public Nullable<int> DirectionId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities4 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Directions Directions { get; set; }
        public virtual Events Events { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
